home_button = "css:#navbarSupportedContent > ul > li:nth-of-type(1)"
categories_dropdown = "css:#navbarSupportedContent > ul > li:nth-of-type(2)"
contact_button = "css:#navbarSupportedContent > ul > li:nth-of-type(3)"
signin_button = "css:#navbarSupportedContent > ul > li:nth-of-type(4)"
user_dropdown = "id:user-menu"
products = "class:card-title"

email_field = "id:email"
password_field = "id:password"
login_button = "class:btnSubmit"
