add_to_cart_button = "id:btn-add-to-cart"
decrease_quantity = "id:btn-decrease-quantity"
increase_quantity = "id:btn-increase-quantity"
product_quantity = "css:input[data-test='quantity']"
product_price = "css:[data-test='unit-price']"
cart_button = "id:lblCartCount"
product_added_message = "class:toast-body"
product_name = "css:[data-test='product-name']"
